import React, { useEffect } from 'react';
import Navbar from '../components/Navbar'; import Footer from '../components/Footer';
import { ArrowRight, MapPin } from 'lucide-react';
import { getCity, EXAM_DIRECTORY } from '../data/seo/geoData';
import { updatePageMeta, injectBreadcrumbSchema } from '../utils/seoEngine';
export default function LocationSeoPage({ citySlug, onOpenBooking, onNavigate }) {
 const city=getCity(citySlug);
 useEffect(()=>{ if(!city)return; updatePageMeta({title:'Exam Registration & Test Centres in '+city.name+' | Testly',description:'GRE, IELTS, TOEFL, PTE, GMAT and other international exam registration guidance for '+city.name+', '+city.state+'. Check current fees, provider test-centre information and booking steps.',canonicalUrl:'https://www.testly.co.in/locations/'+city.slug}); injectBreadcrumbSchema([{name:'Home',url:'https://www.testly.co.in/'},{name:'Locations',url:'https://www.testly.co.in/locations'},{name:city.name,url:'https://www.testly.co.in/locations/'+city.slug}]); },[city]);
 if(!city)return null;
 return <div className="min-h-screen bg-[#FAF9F6] flex flex-col text-slate-900"><Navbar onOpenBooking={onOpenBooking} onNavigate={onNavigate}/><main className="flex-grow">
 <section className="py-16 bg-white border-b border-slate-200"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><span className="text-xs font-bold uppercase tracking-wider text-blue-700">{city.region} · {city.state}</span><h1 className="mt-3 text-4xl sm:text-5xl font-serif tracking-tight">International Exam Registration in {city.name}</h1><p className="mt-5 max-w-3xl text-lg text-slate-600 leading-relaxed">{city.note} Testly helps candidates understand registration, compare current fee information and reach the right official provider page. Testly does not operate or represent every test centre.</p><div className="mt-8 rounded-2xl border border-slate-200 bg-[#FAF9F6] p-5"><div className="flex items-start gap-3"><MapPin className="w-5 h-5 text-blue-700 mt-0.5"/><div><h2 className="font-bold">Common local search areas</h2><p className="mt-2 text-sm text-slate-600">{city.areas.join(' · ')}</p></div></div></div></div></section>
 <section className="py-14"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><h2 className="text-2xl font-bold">Exams in {city.name}</h2><div className="mt-5 grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{EXAM_DIRECTORY.map(exam=><button key={exam.slug} onClick={()=>onNavigate('/locations/'+city.slug+'/'+exam.slug)} className="bg-white border border-slate-200 rounded-2xl p-5 text-left hover:border-blue-300"><h3 className="font-bold">{exam.label}</h3><p className="mt-2 text-sm text-slate-600">Fees, registration, test-centre guidance and preparation.</p><span className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-blue-700">Open local guide <ArrowRight className="w-3 h-3"/></span></button>)}</div></div></section>
 <section className="py-14 bg-white border-t border-slate-200"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8 grid md:grid-cols-3 gap-4"><div className="border border-slate-200 rounded-2xl p-5"><h2 className="font-bold">1. Verify the provider</h2><p className="mt-2 text-sm text-slate-600">Use the official exam provider's current India booking flow for live dates, locations and final pricing.</p></div><div className="border border-slate-200 rounded-2xl p-5"><h2 className="font-bold">2. Check your ID</h2><p className="mt-2 text-sm text-slate-600">Make sure your registration details match the identity document accepted for the exam.</p></div><div className="border border-slate-200 rounded-2xl p-5"><h2 className="font-bold">3. Plan the visit</h2><p className="mt-2 text-sm text-slate-600">Confirm the exact venue, delivery mode, arrival time and cancellation rules before payment.</p></div></div></section>
 </main><Footer onNavigate={onNavigate} onOpenAdmin={()=>onNavigate('/admin')}/></div>;
}