/**
 * Dynamic Test Form Generator for Testly Practice Engine
 * Composes standardized test forms (e.g., GRE Mock #001, TOEFL Form #1)
 * from item pools based on exam specifications and Item Response Theory (IRT) difficulty targets.
 * 
 * Includes legal mock indicators and non-affiliation disclaimers on every generated form.
 */

import { EXAM_CONFIGURATIONS } from '../data/examConfigurations.js';
import { QUESTION_BANK } from '../data/questionBank.js';

export function generateTestForm(examId = 'GRE', formIndex = 1) {
  const config = EXAM_CONFIGURATIONS[examId] || EXAM_CONFIGURATIONS.GRE;
  const formId = `${examId}-MOCK-${String(formIndex).padStart(3, '0')}`;

  const legalNotice = {
    isUnofficialMock: true,
    badgeText: 'UNOFFICIAL PRACTICE ENGINE',
    disclaimer: `This test form (${formId}) is an independent practice tool developed by Testly. It is not affiliated with, endorsed by, or approved by official test makers (ETS, GMAC, IDP, Pearson, LSAC, or Duolingo).`,
    scoreDisclaimer: 'Scores generated by this simulator are Testly Estimated Practice Scores based on IRT modeling and do not guarantee official exam performance.'
  };

  const pool = QUESTION_BANK[examId] || QUESTION_BANK.GRE || [];

  // Filter items by section type
  const buildSectionQuestions = (sectionConfig) => {
    const matching = pool.filter(q => 
      !sectionConfig.sectionType || q.sectionType === sectionConfig.sectionType || q.type === sectionConfig.type
    );

    if (matching.length > 0) {
      return matching;
    }

    // Fallback item pool if specific section filter yields empty
    return pool.slice(0, sectionConfig.questionCount || 10);
  };

  const sections = config.sections.map((secConfig, idx) => ({
    ...secConfig,
    sectionIndex: idx,
    questions: buildSectionQuestions(secConfig)
  }));

  return {
    formId,
    examId,
    examTitle: `${config.title} Practice Mock #${String(formIndex).padStart(3, '0')}`,
    formIndex,
    legalNotice,
    config,
    sections,
    createdAt: new Date().toISOString()
  };
}

export function listAvailableForms(examId = 'GRE') {
  return [
    { id: `${examId}-MOCK-001`, title: `${examId} Practice Mock #001 (Standard)`, difficulty: 'Medium', questionsCount: 54 },
    { id: `${examId}-MOCK-002`, title: `${examId} Practice Mock #002 (Hard Adaptive)`, difficulty: 'Hard', questionsCount: 54 },
    { id: `${examId}-MOCK-003`, title: `${examId} Practice Mock #003 (Diagnostic)`, difficulty: 'Adaptive', questionsCount: 54 },
  ];
}
